#pragma once
const int KeywordNumStart = 101;
const int KeywordNumEnd = 197;
const int OperatorNumStart = 201;
const int OperatorNumEnd = 242;
const int DelimiterNumStart = 301;
const int DelimiterNumEnd = 308;
const int WordTypeNumStart = 401;
const int WordTypeNumEnd = 405;

const char* SynCoding[500] = {
	// 0
	"",
	// 1-100
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	// 101-200 - 关键字
	"auto","bool","break","case","catch",
	"char","class","const","const_cast","continue",
	"decltype","default","delete","do","double",
	"dynamic_cast","else","enum","explicit","export",
	"extern","false","float","for","friend",
	"goto","if","inline","int","long",
	"mutable","namespace","new","noexcept","not_eq",
	"nullptr","operator","or","or_eq","private",
	"protected","public","register","reinterpret_cast","return",
	"short","signed","sizeof","static","static_assert",
	"static_cast","struct","switch","template","this",
	"thread_local","throw","true","try","typedef",
	"typeid","typename","union","unsigned","using",
	"virtual","void","volatile","wchar_t","while",
	"xor","xor_eq","alignas","alignof","constexpr",
	"decltype","final","noexcept","nullptr","static_assert",
	"thread_local","decltype(auto)","return_type","[[fallthrough]]","[[nodiscard]]",
	"[[maybe_unused]]","if constexpr","structured_bindings","consteval","constinit",
	"co_await","co_return","co_yield","requires","import",
	"module","concept","","","",
	// 201-300 - 运算符
	"+","-","*","/","%",
	"++","--","==","!=",">",
	"<",">=","<=","&&","||",
	"!","&","|","^","~",
	"<<",">>","=","+=","-=",
	"*=","/=","%=","&=","|=",
	"^=","<<=",">>=","?",":",
	".","->","::","(",")",
	"[","]","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	// 301-400 - 界符
	"//","/*","*/","{","}",
	";",",","\"","\'","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	// 401-500 - 单词类别
	"-标识符-","-字符-","-字符串-","-整数-","-实数-",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","","",
	"","","","",
};